#!/bin/sh

rosdistro () {
    # ROS2
    if [[ $1 = "eloquent" ]] || [[ $1 = "dashing" ]]; then
        source /opt/ros/$1/setup.zsh
        export ROS_HOME=~/.ros
        source /opt/ros/$1/share/ros2cli/environment/ros2-argcomplete.zsh
        if [ -e $HOME/ros/$1/install ]; then
            . $HOME/ros/$1/install/local_setup.zsh
        fi
    # ROS1
    elif [[ $1 = "melodic" ]]; then
        source /opt/ros/$1/setup.zsh
        export ROS_HOME=~/.ros
        source `catkin locate --shell-verbs`
        if [ -e $HOME/ros/$1/devel ]; then
            source $HOME/ros/$1/devel/setup.zsh
            export ROS_WORKSPACE=$HOME/ros/$1
        fi
    fi
    env | grep ROS
}
